# Setup
title: Insignificant Truths
url: https://yaw.yiadom.org
paginate: 5
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Yaw Boakye
  url: https://yaw.yiadom.org
  email: wheresyaw@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Archive
    url: /archive

  - title: About
    url: /about
